# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(default=' '),
        ),
    ]
